### ISSUE TITLE
Option to forcefully maintain high resolution images

### ISSUE THREAD

**Issue by fysloc** [ronelm2000/wsmtools#13]
Currently, some multi-release sets (ie. Little Busters) will create a full grid of 2600x1850 due to a slightly smaller resolution for older sets. This creates difficult to read images of otherwise legible original images. Suggesting a flag to forcefully maintain full grid resolution and scale up images to match the grid, as opposed to scaling down images to match a smaller grid.

**Comment by ronelm2000** [comment]
The reason for some of those low res images is very likely because the yuyutei/jktcg post-processor failed to find the images, so it's using the one EncoreDecks uses, which is the original WS site.

That being said, I'll work on this when I can.

The flag will be called `upscaling`, executed like this:
```ps
./wstools export encore_deck_link --with upscaling --out sharex
```

**Comment by ronelm2000** [comment]
See the latest build on [GitHub Actions](https://github.com/ronelm2000/wsmtools/actions/runs/186478855) for the new change and test it yourself.

**Comment by fysloc** [comment]
> See the latest build on [GitHub Actions](https://github.com/ronelm2000/wsmtools/actions/runs/186478855) for the new change and test it yourself.

Tested it and it is working as expected. Great work!

**Comment by ronelm2000** [comment]
Thanks. This should be ready for the next major release.
