### ISSUE TITLE
Cockatrice export

### ISSUE THREAD

**Issue by Dryadne** [ronelm2000/wsmtools#20]
Good day,

I am attempting to export a deck from Cockatrice to use in TTS. The XML file that is being used is the community one for all cards. I have parsed the 2 sets that are required for this deck and I am now getting the below error for the export. 

Thanks,
Chris

![image](https://user-images.githubusercontent.com/20666956/97859606-c6572880-1cf8-11eb-8e59-f808ff661f6e.png)

**Comment by ronelm2000** [comment]
Can you provide the `.cod` file so that I look into it?

**Comment by Dryadne** [comment]
Yes, No problem
[GFB.zip](https://github.com/ronelm2000/wsmtools/files/5504770/GFB.zip)

**Comment by ronelm2000** [comment]
There was a change in Cockatrice's cod format, which caused the issue.

I also found an extra issue when parsing GFB vol. 2. Because this set contains both W33 and W38, this causes YYT to skip this set. This should be fixed in the latest development build.

Release for this is in progress. Feel free also to test yourself using Actions.

**Comment by Dryadne** [comment]
Thank you,

Just checked with latest in Action and working as intended.
