### ISSUE TITLE
English Prillya not exporting

### ISSUE THREAD

**Issue by Boltasar** [ronelm2000/wsmtools#5]
It seems that the English Prillya set is not being suffixed with EN in Encore decks and keeps being unable to find images. When I try to use images from either the Encore decks or WS-TCG site they keep complaining about ratio being wrong.

**Comment by ronelm2000** [comment]
There's a distinct difference between <https://www.encoredecks.com/?page=1&set=5c7b101d7cd9b718cdbd085e> and <https://www.encoredecks.com/?page=1&set=5c675ebc7cd9b718cdb87d2e>.

Anyway, export issue is caused because unlike other DX sets, including BDML, its current serial format is unique (and EncoreDecks doesn't store the ACTUAL serial proper) so wsmtool's serial format output is totally wrong.

Case in point:
![image](https://user-images.githubusercontent.com/12634987/80049984-028a1f00-8547-11ea-88a5-07253a502b13.png)

**Comment by ronelm2000** [comment]
Should be fixed properly in v0.2.1
