### ISSUE TITLE
Unhandled exception. System.InvalidOperationException

### ISSUE THREAD

**Issue by Yoshi-to** [ronelm2000/wsmtools#61]
Hi,

im trying to export a few Decks and run into an Issue with Decks, that use multiple Sets like Hololive or Sword Art Online.
I use a standard wsttols export [URL] for the export

When I try to export the following Deck [ https://decklog-en.bushiroad.com/view/J8HV]( https://decklog-en.bushiroad.com/view/J8HV) for example i get the following Error Message:

`Unhandled exception. System.InvalidOperationException: The instance of entity type 'WeissSchwarzTrait' cannot be tracked because another instance with the same key value for {'TraitID', 'Serial'} is already being tracked. When replacing owned entities, modify the properties without changing the instance or detach the previous owned entity entry first. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.`

The second Deck [https://www.encoredecks.com/deck/9HkcdZrjq](https://www.encoredecks.com/deck/9HkcdZrjq) is getting an 
`Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: sao/s80-e004sp`
Error.

Can you point me on how to export these two successfully please or what seems to be the Issue ?
Thanks

**Comment by ronelm2000** [comment]
Found issue:
For https://decklog-en.bushiroad.com/view/J8HV
It seems to be null traits (typically from traitless or climaxes) causing the crash in Akiba translated content in EncoreDecks, as well as an issue with some traits being duplicated due to a site errata.

For https://www.encoredecks.com/deck/9HkcdZrjq
This is due to a bug in JKTCG.
